export default {
  news: 'Aktuelles',
  news_entry0_date: '31.05.2017',
  news_entry0_title: 'Erröffnung neuer Praxis',
  news_entry0_text: 'Wir eröffnen demnächst eine zusätltzliche Praxis in Köln >>',
  news_entry1_date: '25.05.2017',
  news_entry1_title: 'Wir suchen Verstärkung',
  news_entry1_text: 'Für den neuen Standort in Düsseldorf suchen wir schnellstmöglich MFA\'s auf die in Details aufgeführte Stellen >>',
  name: 'Unser Anspruch',
  description1: 'Ihr Anliegen ist unsere Mission. Unser Team aus fünf erfahrenen Fachärztinnen und Fachärzten für Diagnostische Radiologie ist für Sie da und berät Sie jederzeit auf höchstem Niveau.',
  description2: 'Durch kontinuierliche Weiterbildung und modernste medizinische Geräte-Technik bieten wir Ihnen Diagnostik auf neuestem Stand der Forschung. Wir möchten, dass Sie sich bei uns rundum wohlfühlen. Daher bieten wir hohen Komfort und ein gehobenes Ambiente ohne Wartezeiten. Empathie und Fachwissen gehören bei uns zusammen. Lernen Sie unsere Ärzte kennen.',
  description4: 'Reichsstraße 59, 40217 Düsseldorf',
  landingPage: 'Mit langjähriger Erfahrung und modernster Technik zur Diagnose und erfolgreichen Behandlung — ohne Wartezeiten!',
  landingPage_p0: 'Sie sind Privatpatient und suchen Ärzte, denen Sie vertrauen können, die mehr als XX Jahre praktizieren und die ein ganzes Spektrum von Untersuchungen aller Art rund um Radiologie abdecken? Dann hat Ihre Suche endlich ein Ende gefunden: Bei uns sind Sie richtig.',
  landingPage_p1: 'Haben Sie Schmerzen oder sonstige gesundheitliche Beschwerden? Dann warten Sie nicht länger. Denn ohne rechtzeitige Diagnostizierung Ihres Problems und ohne eine entsprechende Therapie könnte sich die Situation verschlimmern. Bei uns steht Ihre Gesundheit als oberste Priorität, wir sind jederzeit für Sie da, um Ihnen zu helfen. Dank unserem erfahrenen Ärzteteam und modernster Ausstattung sorgen wir dafür, dass Ihre Schmerzen dauerhaft der Vergangenheit angehören und Sie Ihr Leben unbeschwert weiter genießen können.',
  landingPage_p2: 'Wir versuchen Ihren Besuch bei uns so angenehm wie möglich zu gestalten und die Wartezeiten minimal zu halten.',
  landingPage_p3: 'Auf dieser Seite finden Sie alle Informationen rund um unser Dienstleistungsangebot, unsere Ärzte und Behandlungsmöglichkeiten.',
};
