export default {
  news: 'Aktuelles',
  news_entry0_date: '31.05.2017',
  news_entry0_title: 'Erröffnung neuer Praxis',
  news_entry0_text: 'Wir eröffnen demnächst eine zusätltzliche Praxis in Köln >>',
  news_entry1_date: '25.05.2017',
  news_entry1_title: 'Wir suchen Verstärkung',
  news_entry1_text: 'Für den neuen Standort in Düsseldorf suchen wir schnellstmöglich MFA\'s auf die in Details aufgeführte Stellen >>',
  name: 'Praxis',
  description1: 'Wir von der Radiologischen Gemeinschaftspraxis kümmern uns um Ihre Schmerzen und Beschwerden. Wir stellen die richtigen Diagnosen mit einer anschließenden speziell auf Sie abgestimmten Therapie.',
  description2: 'Wir behandeln nicht nur Patienten aus ganz Deutschland, sondern auch Patienten aus aller Welt. Das Team aus Radiologen bietet Privat- und Kassenpatienten ein breites Spektrum an Behandlungsmöglichkeiten. In unserer Praxis stehen wir für zeitgemäße Diagnostik, Labortechnik und Therapie aus einer Hand. Unsere Philosophie richtet sich nach unseren Patienten. In unsere Praxis in Duisburg legen wir höchsten Wert auf Ihre Zufriedenheit und Ihr Wohlbefinden, damit Sie Ihr Leben wieder aktiv und ohne Schmerzen genießen können.',
  description3: 'Auf den folgenden Seiten finden Sie hilfreiche Informationen zu unseren Ärzte- und Praxisteams, zum Leistungsspektrum der Praxis sowie zu unserem speziellen Patientenservice. Selbstverständlich beantworten wir Ihre Fragen auch gerne persönlich am Telefon.',
  description4: 'Reichsstraße 59, 40217 Düsseldorf',
  landingPage: 'Mit langjähriger Erfahrung und modernster Technik zur Diagnose und erfolgreichen Behandlung — ohne Wartezeiten!',
  landingPage_p0: 'Sie sind Privatpatient und suchen Ärzte, denen Sie vertrauen können, die mehr als XX Jahre praktizieren und die ein ganzes Spektrum von Untersuchungen aller Art rund um Radiologie abdecken? Dann hat Ihre Suche endlich ein Ende gefunden: Bei uns sind Sie richtig.',
  landingPage_p1: 'Haben Sie Schmerzen oder sonstige gesundheitliche Beschwerden? Dann warten Sie nicht länger. Denn ohne rechtzeitige Diagnostizierung Ihres Problems und ohne eine entsprechende Therapie könnte sich die Situation verschlimmern. Bei uns steht Ihre Gesundheit als oberste Priorität, wir sind jederzeit für Sie da, um Ihnen zu helfen. Dank unserem erfahrenen Ärzteteam und modernster Ausstattung sorgen wir dafür, dass Ihre Schmerzen dauerhaft der Vergangenheit angehören und Sie Ihr Leben unbeschwert weiter genießen können.',
  landingPage_p2: 'Wir versuchen Ihren Besuch bei uns so angenehm wie möglich zu gestalten und die Wartezeiten minimal zu halten.',
  landingPage_p3: 'Auf dieser Seite finden Sie alle Informationen rund um unser Dienstleistungsangebot, unsere Ärzte und Behandlungsmöglichkeiten.',
};
